In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv("Train.csv").values

In [43]:
data

array([[ 2.93416239e-01, -9.45598713e-01, -4.21105147e-01,
         4.06816021e-01,  5.25661832e-01, -8.21546666e+01],
       [-8.36084081e-01, -1.89228039e-01, -7.76402618e-01,
        -1.05383124e+00,  5.97996852e-01, -4.88979602e+01],
       [ 2.36425114e-01,  1.32836018e-01, -1.47722982e-01,
         6.99853963e-01, -1.87364163e-01,  7.72703707e+01],
       ...,
       [ 1.04417694e+00, -8.99206485e-01,  1.73039905e+00,
        -1.87105676e+00,  4.42519647e-01, -1.07510508e+02],
       [-1.26917290e+00, -5.05215916e-03,  1.85766873e+00,
        -1.08036482e+00,  7.36333937e-01, -4.73415578e+01],
       [-1.88400025e+00, -8.49427430e-01, -1.45227035e+00,
         4.88613076e-01,  1.45957580e+00, -1.15939003e+02]])

In [44]:
data.shape


(1600, 6)

In [45]:
X = data[:,:-1]

In [46]:
X.shape

(1600, 5)

In [47]:
Y = data[:,-1]

In [48]:
Y

array([ -82.15466656,  -48.89796018,   77.2703707 , ..., -107.51050797,
        -47.34155781, -115.93900296])

In [49]:
def hypothesis(X, theta):
    return np.dot(X, theta)



def error(X, Y, theta):
    hx = hypothesis(X, theta)
    err = np.sum((hx - Y)**2)
    
    return err/X.shape[0]

def gradient(X,  Y, theta):
    hx= hypothesis(X, theta)
    diff = (hx - Y)
    return np.dot(X.T, diff)/X.shape[0]



def gradient_descent(X, Y, lr= 0.1, max_itr = 100):
    m, n = X.shape
    error_list = []
    theta = np.zeros((n,))
    
    for i in range(max_itr):
        e  = error(X , Y, theta)
        error_list.append(e)
        
        grad = gradient(X, Y, theta)
        theta = theta - lr*grad
        
    return theta, error_list

In [50]:
mu = X.mean(axis=0)
sigma = X.std(axis=0)
X = (X-mu)/sigma

In [51]:
ones = np.ones((X.shape[0], 1))
X_ = np.hstack((ones, X))
X_.shape

(1600, 6)

In [52]:
theta,err_list = gradient_descent(X,Y)

In [53]:
theta

array([29.59234868, 94.64766952,  8.37318663, 45.52116937,  2.46359567])

##Prediction of the test data

In [54]:
X_test = pd.read_csv("Test/Test.csv")

In [55]:
X_test = (X_test-mu)/sigma

In [57]:
theta.shape

(5,)

In [36]:
y_pred = hypothesis(X_test,theta)

In [41]:
y_pred
df = pd.DataFrame(data= y_pred, columns=['target'])
df.insert(0, 'Id', range(0,len(df)))
df.to_csv("air_quality_pred.csv", index=False)

In [39]:
X_test.shape

(400, 5)